### ISSUE TITLE
Top 200 crawling freezes after first batch

### ISSUE THREAD

**Issue by RodolfoFigueroa** [kelvingakuo/fycharts#4]
Running the first example in the **Sample Usage** section writes the first 200 songs (those corresponding to 2017-01-01, global) correctly, but it then freezes. 

**Edit**: The issue is that the crawler is trying to fetch the Top 200 for Andorra (the first region after 'global'), [which no longer seems to be supported](https://spotifycharts.com/regional/ad/daily/latest).

**Edit 2:** The same issue occurs when trying to fetch the [global 200 chart for 2017-02-23](https://spotifycharts.com/regional/global/daily/2017-02-23), which doesn't exist.

**Comment by kelvingakuo** [comment]
Working on a patch. Thank you @RodolfoFigueroa

**Comment by kelvingakuo** [comment]
Fixed with v4.0.2
